version: "3.9"

services:
  yacc32:
    build: .
    platform: linux/amd64   # for√ßa arquitetura x86
    container_name: yacc32
    working_dir: /workspace
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
